### ISSUE TITLE
Question: how does the T2 ISO get the T2 kernel installed?

### ISSUE THREAD

**Issue by killajoe** [t2linux/EOS-calamares_config_t2#1]
Is there a custom Repo for zthe kernel or is it only available for offline installs?
Can not find any hint in the code nor on the wiki.
![2023-12-14_10-22](https://github.com/t2linux/EOS-calamares_config_t2/assets/16797647/2fd66c41-5d3b-49fe-95b3-678370b85018)

**Comment by NoaHimesaka1873** [comment]
It's custom repo! @killajoe 
https://mirror.funami.tech/arch-mact2/os/x86_64
